### ISSUE TITLE
Define parameter constraints by parameter name

### ISSUE THREAD

**Issue by JohannesGaessler** [dsavoiu/kafe2#153]
As of right now parameter constraints need to be defined with the parameter index when using kafe2go.
We should at some point implement the option to specify a parameter name instead.

**Comment by Citiroller** [comment]
This was my plan for one of the next updates for kafe2go I'm working on right now. This now already works for parameter limits, fixation and the parameter formatters.

The name right now is always the name of the argument inside the function. Note that the display name and latex name are just for display in the terminal and matplotlib outputs. The (display-)"name" for parameter formatters can therefore be something completely different than the actual argument name of the function.

Current syntax for arg_formatters:
```
arg_formatters:
  arg_name_1: latex_name_1  # now the arg_name will be used as display name for the terminal output
  arg_name_2:  # different syntax when specifying display name
    name: display_name_2
    latex_name: latex_name_2
```

**Comment by JohannesGaessler** [comment]
If you change the syntax of kafe2go, please make sure that the old syntax is still supported.

**Comment by JohannesGaessler** [comment]
Okay, after consulting with Günter changes to the syntax seem to be acceptable after all.

**Comment by Citiroller** [comment]
This was already possible via the `name` keywrod.
I've added the possibility for simple constraints to be defined via a dictionary:
```
parameter_constraints:
  a:
    value: 1.0
    uncertainty: 0.5
  b:
    value: 1.0
    uncertainty: 0.05
  relative: true
```
If a matrix uncertainty is included it needs to be done the old way via a list (nothing new here):
```
parameter_constraints:
      - type: simple
        index: 0
        value: 0.1
        uncertainty: 1.0
      - type: simple
        name: sigma
        value: 1.0
        uncertainty: 0.5
      - type: matrix
        names: [sigma, mu]
        values: [1.3, 2.5]
        matrix: [[1.1, 0.1], [0.1, 2.4]]
```
`type: simple` can now be omitted as well to further simplify the interface.
